In [1]:
import pandas as pd
import numpy as np

Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [4]:
a1 = np.random.choice(a,(2,3))
a2 = np.random.choice(a,(3,3))
a3 = np.random.choice(a,(3,4))
a4 = np.random.choice(a,(4,4))
a5= np.random.choice(a,(2,2))
a5

array([[19, 15],
       [14, 17]])

Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [10]:
b1 = a.reshape(3, -1)
b2 = a.reshape(2, -1)
b3 = a.reshape(4, -1)
b4 = a.reshape(-1, 3)
b5 = a.reshape(-1, 4)
b2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Нет, нельзя так как каждая строчка будет отдельным списком

Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [30]:
a5 = np.random.normal(size = (3,4), loc=0.0, scale = 1.0)
a5.flatten()

array([-0.25607709, -1.03369334, -0.09715784,  0.44838255, -0.77588724,
       -0.13043756, -0.57349497, -0.69354234,  0.49539042,  0.03987944,
        2.19356422, -0.49892293])

Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [26]:
a = np.arange(20,0,-2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


Задание 7 
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [29]:
b = np.arange(20,1,-2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [32]:
a = np.zeros((4,5))
b = np.ones((5,5))
np.concatenate((a, b), axis=0)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [43]:
a = np.arange(0,12)
A = np.random.choice(a,(4,3))
B = A@A.T
B

array([[ 45,  36,  45,  42],
       [ 36,  61,  76,  70],
       [ 45,  76, 145, 142],
       [ 42,  70, 142, 140]])

Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [44]:
np.random.rand(42)

array([0.16122129, 0.92969765, 0.80812038, 0.63340376, 0.87146059,
       0.80367208, 0.18657006, 0.892559  , 0.53934224, 0.80744016,
       0.8960913 , 0.31800347, 0.11005192, 0.22793516, 0.42710779,
       0.81801477, 0.86073058, 0.00695213, 0.5107473 , 0.417411  ,
       0.22210781, 0.11986537, 0.33761517, 0.9429097 , 0.32320293,
       0.51879062, 0.70301896, 0.3636296 , 0.97178208, 0.96244729,
       0.2517823 , 0.49724851, 0.30087831, 0.28484049, 0.03688695,
       0.60956433, 0.50267902, 0.05147875, 0.27864646, 0.90826589,
       0.23956189, 0.14489487])

Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [59]:
с = np.random.randint(0,16, size = 16)

Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [79]:
C = с.reshape(4, 4)
D = B+C*10
np.linalg.matrix_rank(D)

array([[ 3, 11, 10,  3],
       [ 2,  9,  2, 14],
       [ 2,  3, 15,  6],
       [ 3,  8,  0,  7]])

In [80]:
np.linalg.det(D)

array([[ 45,  36,  45,  42],
       [ 36,  61,  76,  70],
       [ 45,  76, 145, 142],
       [ 42,  70, 142, 140]])

In [76]:
D_inv= np.linalg.inv(D)

Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [77]:
D_inv[D_inv>0] = 1
D_inv[D_inv<0] = 0
D_inv

array([[0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [78]:
E = np.where(D_inv, B, C)
E

array([[  3,  11,  10,  42],
       [ 36,  61,  76,  14],
       [ 45,  76, 145,   6],
       [  3,   8,   0, 140]])